# Generated by Django 3.2.7 on 2021-10-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='csv',
            name='tienda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proyecto_register.tienda'),
            preserve_default=False,
        ),
    ]
